/**
 * Development server for mermaid samples — replaces the former hand-rolled
 * dev.ts (Node http + fs.watch + SSE live-reload) with Vite, standardizing
 * on it as this repo's dev server. See zombie-mermaid#307.
 *
 * `packages/site/index.ts`/`packages/site/editor.ts` still do the actual work: each is a one-shot
 * generator that bundles the browser code — via Vite's own `build()` API,
 * see scripts/vite-bundle.ts — and inlines it, the sample data, and the
 * highlighted source into one self-contained HTML file — the same file
 * CI's visual-regression suite and the published GitHub Pages site
 * (`build:site`) use. This config's job is only to re-run those generators
 * on a relevant file change and serve the result, with Vite providing the
 * HTTP server, file watching, and HMR websocket (replacing the old custom
 * SSE channel) for free.
 *
 * Usage: `pnpm run dev` (`vite`). Port defaults to 3456; override with the
 * PORT env var, e.g. `PORT=3457 pnpm run dev` — handy for running more than
 * one instance at once (a worktree alongside the main checkout, say).
 *
 * Routes:
 *   /                → index.html (marketing home page, generated by packages/site/index.ts)
 *   /editor          → editor.html (live diagram editor, generated by packages/site/editor.ts)
 *   /diagrams/**     → diagrams/** (per-type/per-theme SEO pages, generated by packages/site/pages.ts)
 *   /fork-fixes.html → fork-fixes.html (before/after showcase, generated by packages/site/fork-fixes.ts)
 *   /dashboard.html  → dashboard.html (maintenance dashboard, generated by packages/site/dashboard.ts)
 *   /blog/**         → blog/** (posts + index + feed.xml, generated by packages/site/blog.ts)
 */

import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'
import {
  defineConfig,
  normalizePath,
  type Plugin,
  type ViteDevServer,
} from 'vite'

const ROOT = dirname(fileURLToPath(import.meta.url))

// Resolve the local tsx CLI so rebuilds don't depend on PATH/.bin symlinks.
const tsxCli = fileURLToPath(import.meta.resolve('tsx/cli'))

/**
 * Registers the `.module.css` loader hook (zombie-mermaid#1103) alongside
 * tsx's own — via `NODE_OPTIONS`, not an extra `--import` argv flag on this
 * spawn, because tsx's CLI re-execs a fresh child process to actually run
 * the file; only `NODE_OPTIONS` (an env var) survives that re-exec, an
 * argv flag given to *this* spawn wouldn't (confirmed empirically while
 * building the hook). The path is relative to `cwd: ROOT` below, matching
 * the package.json scripts' own `--import ./scripts/css-module-register.mjs`
 * wiring. Appended to whatever `NODE_OPTIONS` this process already has,
 * rather than replacing it, so an operator's own setting (e.g.
 * `--max-old-space-size`) still applies.
 */
const cssModuleLoaderNodeOptions =
  '--import ./scripts/css-module-register.mjs' +
  (process.env.NODE_OPTIONS ? ` ${process.env.NODE_OPTIONS}` : '')

function runTsx(file: string): Promise<number | null> {
  return new Promise((resolve) => {
    const proc = spawn(process.execPath, [tsxCli, file], {
      cwd: ROOT,
      stdio: 'inherit',
      env: { ...process.env, NODE_OPTIONS: cssModuleLoaderNodeOptions },
    })
    proc.on('exit', (exitCode) => resolve(exitCode))
  })
}

// Only these top-level paths are watched (explicitly added below) and feed
// the rebuild — everything else (.git/, node_modules/, .claude/worktrees/,
// test-results/, etc.) is deliberately never added to the watcher at all,
// rather than added-then-filtered, so it's not scanned in the first place.
const WATCHED_PREFIXES = [
  'src/',
  'demo/',
  'editor/',
  'packages/site/index.ts',
  'packages/site/samples-data.ts',
  'packages/site/editor.ts',
  'packages/site/fork-fixes.ts',
  'packages/site/pages.ts',
  'packages/site/dashboard.ts',
  'packages/site/blog.ts',
  'blog-posts/',
]

function isWatchedPath(relPath: string): boolean {
  return WATCHED_PREFIXES.some(
    (prefix) => relPath === prefix || relPath.startsWith(prefix),
  )
}

let building = false
// Set when a change arrives while a rebuild is already running, so it isn't
// dropped on the floor — rebuild() runs once more right after the current
// one finishes, instead of leaving index.html/editor.html stale until some
// later, unrelated change happens to trigger another rebuild.
let rebuildQueued = false
async function rebuild(server: ViteDevServer): Promise<void> {
  if (building) {
    rebuildQueued = true
    return
  }
  building = true
  console.log('\x1b[36m[dev]\x1b[0m Rebuilding samples...')
  const t0 = performance.now()

  // blog.ts appends to the sitemap.xml pages.ts writes (it errors if that
  // file doesn't already have a well-formed </urlset>), so it can't run
  // concurrently with pages.ts — same ordering build:site enforces serially.
  // Everything else here is independent and safe to run in parallel.
  const [samplesExit, editorExit, forkFixesExit, dashboardExit, pagesExit] =
    await Promise.all([
      runTsx(join(ROOT, 'packages/site/index.ts')),
      runTsx(join(ROOT, 'packages/site/editor.ts')),
      runTsx(join(ROOT, 'packages/site/fork-fixes.ts')),
      runTsx(join(ROOT, 'packages/site/dashboard.ts')),
      runTsx(join(ROOT, 'packages/site/pages.ts')),
    ])
  const blogExit =
    pagesExit === 0 ? await runTsx(join(ROOT, 'packages/site/blog.ts')) : null

  building = false
  const ms = (performance.now() - t0).toFixed(0)
  if (
    samplesExit === 0 &&
    editorExit === 0 &&
    forkFixesExit === 0 &&
    dashboardExit === 0 &&
    pagesExit === 0 &&
    blogExit === 0
  ) {
    console.log(`\x1b[32m[dev]\x1b[0m Rebuilt in ${ms}ms`)
    server.ws.send({ type: 'full-reload' })
  } else {
    console.error(
      `\x1b[31m[dev]\x1b[0m Build failed (samples exit ${samplesExit}, editor exit ${editorExit}, fork-fixes exit ${forkFixesExit}, dashboard exit ${dashboardExit}, pages exit ${pagesExit}, blog exit ${blogExit})`,
    )
  }

  if (rebuildQueued) {
    rebuildQueued = false
    void rebuild(server)
  }
}

function samplesRebuildPlugin(): Plugin {
  let debounce: NodeJS.Timeout | null = null

  return {
    name: 'zombie-mermaid-samples-rebuild',
    async configureServer(server) {
      // Initial build before the server starts accepting requests.
      await rebuild(server)

      // Vite's watcher only watches paths pulled into its module graph by
      // default — and since the samples/editor pages are served directly
      // from disk (see the middleware below), bypassing that graph
      // entirely, nothing would otherwise tell chokidar these paths exist.
      server.watcher.add(WATCHED_PREFIXES.map((prefix) => join(ROOT, prefix)))

      server.watcher.on('all', (_event, file) => {
        // node:path's relative() uses the OS separator — normalize to
        // forward slashes (matching WATCHED_PREFIXES) so this doesn't
        // silently stop matching on Windows.
        const relPath = normalizePath(relative(ROOT, file))
        // Ignore the generated outputs themselves, else a rebuild's own
        // writes would trigger another rebuild.
        if (
          relPath === 'index.html' ||
          relPath === 'editor.html' ||
          relPath === 'fork-fixes.html' ||
          relPath === 'dashboard.html' ||
          relPath === 'sitemap.xml' ||
          relPath.startsWith('blog/')
        )
          return
        if (!isWatchedPath(relPath)) return
        if (debounce) clearTimeout(debounce)
        debounce = setTimeout(() => {
          console.log(`\x1b[90m[dev]\x1b[0m Change detected: ${relPath}`)
          void rebuild(server)
        }, 150)
      })

      // Serve the generated HTML directly (bypassing Vite's default
      // index.html-from-disk handling, since ours is a generated file that
      // may not exist yet on a fresh checkout) with just the Vite HMR
      // client script spliced in. Deliberately *not* routed through
      // server.transformIndexHtml(): that runs Vite's full HTML plugin
      // pipeline, which also tries to extract and transform inline
      // <style>/<script> blocks as if they were untransformed source — ours
      // are already-bundled, self-contained output (the same file the
      // static build and CI's visual-regression suite use), so there's
      // nothing for Vite to usefully transform, and doing so anyway once
      // errored out entirely on this page's large inlined stylesheet.
      server.middlewares.use(async (req, res, next) => {
        const url = (req.url ?? '/').split('?')[0]!

        // /diagrams and /blog serve a *directory's* index.html
        // (diagrams/index.html, blog/index.html), and those pages' CSS is
        // included via a relative href (`assets/diagram-page.css`,
        // `assets/blog.css`) so the built site stays portable to any
        // hosted subpath — see pages.ts/blog.ts's own cssHref comments.
        // A relative href only resolves correctly against a URL whose
        // final segment is a trailing slash or filename, never a bare
        // directory name: requesting the bare URL (no trailing slash)
        // resolves `assets/blog.css` one directory too high and 404s,
        // silently dropping the page's own layout CSS (zombie-mermaid#1058).
        // Production (GitHub Pages) already 301-redirects a bare
        // directory request to add the trailing slash (verified via
        // `curl -I https://dfadler.github.io/zombie-mermaid/blog`), so
        // mirror that here instead of serving the directory's content
        // straight under the bare URL.
        if (url === '/diagrams' || url === '/blog') {
          res.statusCode = 301
          res.setHeader('Location', `${url}/`)
          res.end()
          return
        }

        let file: string | null = null
        if (url === '/' || url === '/index.html') file = 'index.html'
        else if (url === '/editor' || url === '/editor.html')
          file = 'editor.html'
        else if (url === '/diagrams/') file = 'diagrams/index.html'
        else if (url.startsWith('/diagrams/')) {
          // pages.ts's own output tree (diagrams/**) — served straight from
          // disk, same as index.html/editor.html above. Guard against path
          // traversal since the URL segment feeds directly into a join().
          const rel = url.replace(/^\/+/, '')
          if (!rel.includes('..')) file = rel
        } else if (url === '/fork-fixes.html') file = 'fork-fixes.html'
        else if (url === '/dashboard.html') file = 'dashboard.html'
        else if (url === '/blog/') file = 'blog/index.html'
        else if (url.startsWith('/blog/')) {
          // blog.ts's own output tree (blog/**: posts, index, feed.xml,
          // assets/blog.css) — same pattern as diagrams/** above, same
          // traversal guard.
          const rel = url.replace(/^\/+/, '')
          if (!rel.includes('..')) file = rel
        }
        if (!file) {
          next()
          return
        }

        const path = join(ROOT, file)
        if (!existsSync(path)) {
          res.statusCode = 404
          res.setHeader('Content-Type', 'text/plain')
          res.end(`${file} not found — build may have failed`)
          return
        }

        // Non-HTML assets under diagrams/ (its stylesheet, sitemap.xml if
        // ever requested this way) are served as-is — the HMR client tag
        // below only makes sense spliced into an HTML document.
        if (!file.endsWith('.html')) {
          const contentType = file.endsWith('.css')
            ? 'text/css'
            : file.endsWith('.xml')
              ? 'application/xml'
              : file.endsWith('.js')
                ? 'text/javascript'
                : 'application/octet-stream'
          res.setHeader('Content-Type', contentType)
          res.end(await readFile(path, 'utf-8'))
          return
        }

        const raw = await readFile(path, 'utf-8')
        const viteClientTag = `  <script type="module" src="/@vite/client"></script>\n</head>`
        const html = raw.includes('</head>')
          ? raw.replace('</head>', viteClientTag)
          : raw
        res.setHeader('Content-Type', 'text/html')
        res.end(html)
      })
    },
  }
}

export default defineConfig({
  root: ROOT,
  server: {
    port: Number(process.env.PORT) || 3456,
  },
  plugins: [samplesRebuildPlugin()],
})
