/**
 * Development server for mermaid samples — replaces the former hand-rolled
 * dev.ts (Node http + fs.watch + SSE live-reload) with Vite, standardizing
 * on it as this repo's dev server. See zombie-mermaid#307.
 *
 * `index.ts`/`editor.ts` still do the actual work: each is a one-shot
 * generator that bundles the browser code (esbuild) and inlines it, the
 * sample data, and the highlighted source into one self-contained HTML
 * file — the same file CI's visual-regression suite and the published
 * GitHub Pages site (`build:site`) use. This config's job is only to
 * re-run those generators on a relevant file change and serve the result,
 * with Vite providing the HTTP server, file watching, and HMR websocket
 * (replacing the old custom SSE channel) for free.
 *
 * Usage: `pnpm run dev` (`vite`). Port defaults to 3456; override with the
 * PORT env var, e.g. `PORT=3457 pnpm run dev` — handy for running more than
 * one instance at once (a worktree alongside the main checkout, say).
 *
 * Routes:
 *   /         → index.html (samples showcase, generated by index.ts)
 *   /editor   → editor.html (live diagram editor, generated by editor.ts)
 */

import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'
import { defineConfig, type Plugin, type ViteDevServer } from 'vite'

const ROOT = dirname(fileURLToPath(import.meta.url))

// Resolve the local tsx CLI so rebuilds don't depend on PATH/.bin symlinks.
const tsxCli = fileURLToPath(import.meta.resolve('tsx/cli'))

function runTsx(file: string): Promise<number | null> {
  return new Promise((resolve) => {
    const proc = spawn(process.execPath, [tsxCli, file], {
      cwd: ROOT,
      stdio: 'inherit',
    })
    proc.on('exit', (exitCode) => resolve(exitCode))
  })
}

// Only these top-level paths are watched (explicitly added below) and feed
// the rebuild — everything else (.git/, node_modules/, .claude/worktrees/,
// test-results/, etc.) is deliberately never added to the watcher at all,
// rather than added-then-filtered, so it's not scanned in the first place.
const WATCHED_PREFIXES = [
  'src/',
  'demo/',
  'editor/',
  'index.ts',
  'samples-data.ts',
  'editor.ts',
  'fork-fixes.ts',
]

function isWatchedPath(relPath: string): boolean {
  return WATCHED_PREFIXES.some(
    (prefix) => relPath === prefix || relPath.startsWith(prefix),
  )
}

let building = false
async function rebuild(server: ViteDevServer): Promise<void> {
  if (building) return
  building = true
  console.log('\x1b[36m[dev]\x1b[0m Rebuilding samples...')
  const t0 = performance.now()

  const [samplesExit, editorExit] = await Promise.all([
    runTsx(join(ROOT, 'index.ts')),
    runTsx(join(ROOT, 'editor.ts')),
  ])

  building = false
  const ms = (performance.now() - t0).toFixed(0)
  if (samplesExit === 0 && editorExit === 0) {
    console.log(`\x1b[32m[dev]\x1b[0m Rebuilt in ${ms}ms`)
    server.ws.send({ type: 'full-reload' })
  } else {
    console.error(
      `\x1b[31m[dev]\x1b[0m Build failed (samples exit ${samplesExit}, editor exit ${editorExit})`,
    )
  }
}

function samplesRebuildPlugin(): Plugin {
  let debounce: NodeJS.Timeout | null = null

  return {
    name: 'zombie-mermaid-samples-rebuild',
    async configureServer(server) {
      // Initial build before the server starts accepting requests.
      await rebuild(server)

      // Vite's watcher only watches paths pulled into its module graph by
      // default — and since the samples/editor pages are served directly
      // from disk (see the middleware below), bypassing that graph
      // entirely, nothing would otherwise tell chokidar these paths exist.
      server.watcher.add(WATCHED_PREFIXES.map((prefix) => join(ROOT, prefix)))

      server.watcher.on('all', (_event, file) => {
        const relPath = relative(ROOT, file)
        // Ignore the generated outputs themselves, else a rebuild's own
        // writes would trigger another rebuild.
        if (relPath === 'index.html' || relPath === 'editor.html') return
        if (!isWatchedPath(relPath)) return
        if (debounce) clearTimeout(debounce)
        debounce = setTimeout(() => {
          console.log(`\x1b[90m[dev]\x1b[0m Change detected: ${relPath}`)
          void rebuild(server)
        }, 150)
      })

      // Serve the generated HTML directly (bypassing Vite's default
      // index.html-from-disk handling, since ours is a generated file that
      // may not exist yet on a fresh checkout) with just the Vite HMR
      // client script spliced in. Deliberately *not* routed through
      // server.transformIndexHtml(): that runs Vite's full HTML plugin
      // pipeline, which also tries to extract and transform inline
      // <style>/<script> blocks as if they were untransformed source — ours
      // are already-bundled, self-contained output (the same file the
      // static build and CI's visual-regression suite use), so there's
      // nothing for Vite to usefully transform, and doing so anyway once
      // errored out entirely on this page's large inlined stylesheet.
      server.middlewares.use(async (req, res, next) => {
        const url = req.url ?? '/'
        const file =
          url === '/' || url === '/index.html'
            ? 'index.html'
            : url === '/editor' || url === '/editor.html'
              ? 'editor.html'
              : null
        if (!file) {
          next()
          return
        }

        const path = join(ROOT, file)
        if (!existsSync(path)) {
          res.statusCode = 404
          res.setHeader('Content-Type', 'text/plain')
          res.end(`${file} not found — build may have failed`)
          return
        }
        const raw = await readFile(path, 'utf-8')
        const viteClientTag = `  <script type="module" src="/@vite/client"></script>\n</head>`
        const html = raw.includes('</head>')
          ? raw.replace('</head>', viteClientTag)
          : raw
        res.setHeader('Content-Type', 'text/html')
        res.end(html)
      })
    },
  }
}

export default defineConfig({
  root: ROOT,
  server: {
    port: Number(process.env.PORT) || 3456,
  },
  plugins: [samplesRebuildPlugin()],
})
