/**
 * URL-hash sharing as React state (zombie-mermaid#810) -- the last slice of
 * the #797 editor rewrite. Replaces `editor/js/sharing.ts`'s
 * `encodeSource()`/`decodeSource()`/`getHashSource()`/`updateHash()` (all
 * deleted by this issue) with the pure functions below plus {@link
 * useEditorSharing}, called directly from `<EditorApp>`'s own body -- the
 * same shape `editor-viewport.ts`'s `useEditorViewport` established for
 * #807.
 *
 * ## Compatibility is the whole point
 *
 * The base64-of-JSON hash format (`{source, theme?}`, `encodeURIComponent`
 * + `unescape`/`escape` around `btoa`/`atob` for non-Latin1 source text) is
 * unchanged byte-for-byte from `editor/js/sharing.ts` -- a link generated by
 * the pre-#810 editor must still load correctly here, and a link generated
 * here must still load in the pre-#810 editor. See
 * `__tests__/dom/editor-sharing.test.ts`'s dedicated round-trip test (a
 * verbatim copy of the old `encodeSource`/`decodeSource` bodies, kept only
 * as a compatibility fixture) for the proof.
 *
 * ## The `window.__editorSharingState` bridge
 *
 * `demo/components/editor-export.ts`'s `copyURL()` (zombie-mermaid#809)
 * already calls `window.__editorSharingState.updateHash()` -- at the time
 * that issue shipped, `sharing.ts` was still legacy and exposed this bridge
 * itself (see that file's own former header comment). Now that sharing is
 * React too, {@link useEditorSharing} registers the exact same bridge shape
 * instead, purely for backward compatibility with `editor-export.ts`'s
 * already-shipped, already-tested call site -- not because a still-legacy
 * module needs it. `editor/js/rendering.ts`'s replacement
 * (`editor-rendering.ts`) doesn't go through this bridge at all: it's in
 * the same React tree now, so it imports {@link updateUrlHash} directly.
 */
import { useLayoutEffect, useRef } from 'react'
import type { EditorRefs, EditorState } from './editor-app.tsx'

declare global {
  interface Window {
    __editorSharingState: {
      updateHash(): void
    }
  }
}

/** Moved verbatim from `editor/js/sharing.ts` (deleted by this issue). */
export function encodeSource(src: string): string {
  try {
    return btoa(unescape(encodeURIComponent(src)))
  } catch {
    return ''
  }
}

/** Moved verbatim from `editor/js/sharing.ts` (deleted by this issue). */
export function decodeSource(b64: string): string {
  try {
    return decodeURIComponent(escape(atob(b64)))
  } catch {
    return ''
  }
}

export interface ParsedHash {
  source: string
  theme?: string
}

/**
 * Pure version of `editor/js/sharing.ts`'s old `getHashSource()` -- takes
 * the raw hash string (no leading `#`, no `window.location` read) and
 * returns the decoded `{source, theme?}` instead of reaching into
 * `state.theme` as a side effect the way the old function did (that
 * function's `setEditorTheme(obj.theme)` call is now the caller's job --
 * see `editor-theme.ts`'s bootstrap effect). Falls back to treating the
 * whole hash as a raw (non-JSON) encoded source string, matching the old
 * function's final `return decodeSource(hash) || null` fallback.
 */
export function parseHash(hash: string): ParsedHash | null {
  if (!hash) return null
  try {
    // JSON.parse's declared return type is `any`, matching
    // editor/js/sharing.ts's original untyped-JS looseness here --
    // `obj.source`/`obj.theme` stay loosely checked on purpose rather than
    // validated, same as before that file had types.
    const obj = JSON.parse(decodeSource(hash))
    if (obj && obj.source) {
      return obj.theme
        ? { source: obj.source, theme: obj.theme }
        : { source: obj.source }
    }
  } catch {
    // fall through to the raw-hash fallback below
  }
  const raw = decodeSource(hash)
  return raw ? { source: raw } : null
}

/**
 * Pure version of `editor/js/sharing.ts`'s old `updateHash()` -- builds the
 * `#`-prefixed encoded hash string for a given (source, theme) pair rather
 * than writing it to `window.location` itself, so the format can be
 * unit-tested without a DOM. `theme` is omitted from the JSON payload when
 * empty, matching the old `if (state.theme) obj.theme = state.theme`.
 */
export function buildHash(source: string, theme: string): string {
  const obj: { source: string; theme?: string } = { source }
  if (theme) obj.theme = theme
  return '#' + encodeSource(JSON.stringify(obj))
}

/**
 * Writes `buildHash(source, theme)` to the URL via `history.replaceState`
 * -- `editor/js/sharing.ts`'s old `updateHash()`'s DOM-writing half.
 * Exported (not just called from {@link useEditorSharing}'s bridge) so
 * `editor-rendering.ts`'s `doRender()` can call it directly after a
 * successful render, the same way it did as a plain same-program import
 * before this issue (`import { updateHash } from './sharing.ts'`) -- no
 * bridge needed for that call site now that both live in the same React
 * tree.
 */
export function updateUrlHash(source: string, theme: string): void {
  window.history.replaceState(null, '', buildHash(source, theme))
}

export interface UseEditorSharingArgs {
  state: EditorState
  refs: { current: EditorRefs | null }
}

/**
 * Registers `window.__editorSharingState` for `editor-export.ts`'s
 * `copyURL()` to call -- see this file's header comment. Call once,
 * unconditionally, from `<EditorApp>`'s own body.
 */
export function useEditorSharing({ state, refs }: UseEditorSharingArgs): void {
  const stateRef = useRef(state)
  stateRef.current = state

  useLayoutEffect(() => {
    window.__editorSharingState = {
      updateHash: () => {
        const r = refs.current
        if (!r) return
        updateUrlHash(r.editor.value, stateRef.current.theme)
      },
    }
  }, [refs])
}
