// @vitest-environment jsdom
/**
 * Proves zombie-mermaid#810's URL-hash sharing React state actually works,
 * replacing `editor/__tests__/sharing.test.ts`'s old `createEditorEnv()` +
 * `window.eval` approach (`encodeSource`/`decodeSource`/`getHashSource`/
 * `updateHash` no longer exist as legacy globals -- #810 moved them to
 * `demo/components/editor-sharing.ts`) with this repo's React Testing
 * Library pattern (`__tests__/dom/rtl-example.test.ts`,
 * `__tests__/dom/editor-viewport.test.ts`):
 *
 * 1. Pure-function unit tests for `encodeSource`, `decodeSource`,
 *    `parseHash`, and `buildHash` -- the same "small pure function, tested
 *    directly" coverage `sharing.test.ts` used to give the equivalent
 *    legacy functions.
 * 2. A dedicated **wire-format compatibility** test: a link generated by
 *    the pre-#810 editor must still load in the post-#810 one, and vice
 *    versa. `editor/js/sharing.ts` is gone, so this keeps a verbatim copy
 *    of its old `encodeSource`/`decodeSource` bodies as a fixture purely to
 *    prove the new functions still agree with them byte-for-byte -- not as
 *    production code to import from anywhere.
 * 3. A real RTL interaction test against a mounted `<EditorApp>`: the
 *    `window.__editorSharingState` bridge `demo/components/editor-export.ts`'s
 *    `copyURL()` (#809) already calls.
 */
import { act, createElement } from 'react'
import { render } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import {
  EditorApp,
  type EditorAppProps,
} from '../../demo/components/editor-app.tsx'
import {
  buildHash,
  decodeSource,
  encodeSource,
  parseHash,
} from '../../demo/components/editor-sharing.ts'

const PROPS: EditorAppProps = {
  themes: [{ key: 'nord', bg: '#2E3440', label: 'Nord' }],
}

describe('encodeSource/decodeSource (#810)', () => {
  it('round-trips arbitrary source text, including non-Latin1 characters', () => {
    const original = 'graph TD\n  A[héllo "world"] --> B{日本語}'
    expect(decodeSource(encodeSource(original))).toBe(original)
  })

  it('decodeSource returns an empty string for malformed base64', () => {
    expect(decodeSource('not-valid-base64!!!')).toBe('')
  })
})

describe('parseHash (#810, moved from editor/js/sharing.ts’s getHashSource)', () => {
  it('returns null for an empty hash', () => {
    expect(parseHash('')).toBeNull()
  })

  it('parses a {source, theme} JSON payload', () => {
    const hash = encodeSource(
      JSON.stringify({ source: 'graph LR\n  X --> Y', theme: 'dracula' }),
    )
    expect(parseHash(hash)).toEqual({
      source: 'graph LR\n  X --> Y',
      theme: 'dracula',
    })
  })

  it('omits theme from the result when absent from the payload', () => {
    const hash = encodeSource(JSON.stringify({ source: 'graph LR\n  X --> Y' }))
    expect(parseHash(hash)).toEqual({ source: 'graph LR\n  X --> Y' })
  })

  it('falls back to treating the whole hash as a raw encoded source when it is not JSON', () => {
    const hash = encodeSource('graph TD\n  A --> B')
    expect(parseHash(hash)).toEqual({ source: 'graph TD\n  A --> B' })
  })

  it('returns null when the hash decodes to nothing usable', () => {
    expect(parseHash('!!!not-base64!!!')).toBeNull()
  })
})

describe('buildHash (#810, moved from editor/js/sharing.ts’s updateHash)', () => {
  it('encodes source and theme, "#"-prefixed', () => {
    const hash = buildHash('graph TD\n  A --> B', 'nord')
    expect(hash.startsWith('#')).toBe(true)
    expect(JSON.parse(decodeSource(hash.slice(1)))).toEqual({
      source: 'graph TD\n  A --> B',
      theme: 'nord',
    })
  })

  it('omits theme from the payload when empty', () => {
    const hash = buildHash('graph TD\n  A --> B', '')
    expect(JSON.parse(decodeSource(hash.slice(1)))).toEqual({
      source: 'graph TD\n  A --> B',
    })
  })
})

/**
 * Verbatim copies of `editor/js/sharing.ts`'s pre-#810 `encodeSource`/
 * `decodeSource` bodies -- kept only as a compatibility fixture (see this
 * file's header comment), never imported by production code.
 */
function oldEncodeSource(src: string): string {
  try {
    return btoa(unescape(encodeURIComponent(src)))
  } catch {
    return ''
  }
}
function oldDecodeSource(b64: string): string {
  try {
    return decodeURIComponent(escape(atob(b64)))
  } catch {
    return ''
  }
}

describe('wire-format compatibility (#810)', () => {
  it('a hash encoded by the OLD (pre-#810) logic decodes correctly with the NEW logic', () => {
    const payload = JSON.stringify({
      source: 'graph TD\n  A[héllo] --> B{日本語}',
      theme: 'one-dark',
    })
    const oldHash = oldEncodeSource(payload)
    expect(JSON.parse(decodeSource(oldHash))).toEqual({
      source: 'graph TD\n  A[héllo] --> B{日本語}',
      theme: 'one-dark',
    })
    // parseHash's own end-to-end contract, not just the raw decode step.
    expect(parseHash(oldHash)).toEqual({
      source: 'graph TD\n  A[héllo] --> B{日本語}',
      theme: 'one-dark',
    })
  })

  it('a hash encoded by the NEW logic decodes correctly with the OLD (pre-#810) logic', () => {
    const hash = buildHash('graph LR\n  X --> Y', 'nord')
    expect(JSON.parse(oldDecodeSource(hash.slice(1)))).toEqual({
      source: 'graph LR\n  X --> Y',
      theme: 'nord',
    })
  })

  it('encodeSource/decodeSource agree byte-for-byte with the old implementation for arbitrary text', () => {
    const sample = 'graph TD\n  A[héllo "world"] --> B{日本語, emoji 🎉}'
    expect(encodeSource(sample)).toBe(oldEncodeSource(sample))
    expect(decodeSource(oldEncodeSource(sample))).toBe(
      oldDecodeSource(encodeSource(sample)),
    )
  })
})

describe('<EditorApp> window.__editorSharingState bridge (#810)', () => {
  it('updateHash() writes the current source + theme to the URL hash', async () => {
    render(createElement(EditorApp, PROPS))
    const textarea = document.getElementById(
      'code-editor',
    ) as HTMLTextAreaElement
    textarea.value = 'graph TD\n  A --> B'

    await act(async () => {
      window.__editorSharingState.updateHash()
      await Promise.resolve()
    })

    expect(JSON.parse(decodeSource(window.location.hash.slice(1)))).toEqual({
      source: 'graph TD\n  A --> B',
    })
  })
})
