/**
 * Writes `docs/development-scripts.md` — the reference list of every
 * `package.json` script — from `package.json`'s `scripts` plus the
 * per-script one-liners in `scripts/script-descriptions.json`.
 *
 * The doc is generated so the list can't drift: `__tests__/development-scripts-doc.test.ts`
 * (run by CI's `test` job) fails when the committed file differs from this
 * script's output, when a script has no description, or when a description
 * names a script that no longer exists. To add or rename a script, edit
 * `package.json` and the JSON file, then run `pnpm run docs:scripts`.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const GROUPS: ReadonlyArray<{ title: string; match: RegExp }> = [
  { title: 'Testing', match: /^test(:|$)|^coverage:/ },
  {
    title: 'Build, lint, and dev server',
    match: /^(build|dev|lint|format|typecheck|prepublishOnly)(:|$)/,
  },
  { title: 'Benchmarks and checks', match: /^(bench|check):/ },
  {
    title: 'Site and asset generators',
    match:
      /^(samples|editor|pages|blog|fork-fixes|dashboard|generate|badge|docs)(:|$)/,
  },
]
const OTHER_TITLE = 'Other tooling'

interface PackageJson {
  scripts: Record<string, string>
}

export function renderDevelopmentScriptsDoc(
  scripts: Record<string, string>,
  descriptions: Record<string, string>,
): string {
  const names = Object.keys(scripts)
  const missing = names.filter((n) => !descriptions[n])
  const orphaned = Object.keys(descriptions).filter((n) => !(n in scripts))
  if (missing.length > 0 || orphaned.length > 0) {
    throw new Error(
      `scripts/script-descriptions.json is out of sync with package.json scripts. ` +
        `Missing descriptions: [${missing.join(', ')}]. Descriptions for unknown scripts: [${orphaned.join(', ')}].`,
    )
  }
  const sections = [...GROUPS.map((g) => g.title), OTHER_TITLE].map(
    (title) => ({
      title,
      lines: [] as string[],
    }),
  )
  for (const name of names) {
    const idx = GROUPS.findIndex((g) => g.match.test(name))
    const section = sections[idx === -1 ? sections.length - 1 : idx]
    section.lines.push(`- \`pnpm run ${name}\` — ${descriptions[name]}`)
  }
  const body = sections
    .filter((s) => s.lines.length > 0)
    .map((s) => `## ${s.title}\n\n${s.lines.join('\n')}`)
    .join('\n\n')
  return (
    `<!-- Generated by scripts/generate-development-scripts-doc.ts from package.json and scripts/script-descriptions.json. Do not edit by hand; run \`pnpm run docs:scripts\`. -->\n\n` +
    `# Development scripts\n\n` +
    `Every \`package.json\` script and what it does. Visual-regression workflow details are in [visual-regression.md](visual-regression.md).\n\n` +
    `${body}\n`
  )
}

const DOC_PATH = fileURLToPath(
  new URL('../docs/development-scripts.md', import.meta.url),
)

export async function generateDevelopmentScriptsDoc(): Promise<string> {
  const pkg = JSON.parse(
    await readFile(new URL('../package.json', import.meta.url), 'utf8'),
  ) as PackageJson
  const descriptions = JSON.parse(
    await readFile(
      new URL('./script-descriptions.json', import.meta.url),
      'utf8',
    ),
  ) as Record<string, string>
  const raw = renderDevelopmentScriptsDoc(pkg.scripts, descriptions)
  const config = await resolveConfig(DOC_PATH)
  return format(raw, { ...config, parser: 'markdown' })
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(DOC_PATH, await generateDevelopmentScriptsDoc())
}
