/**
 * Regenerates the README's hero diagram (hero.svg) from the "Hero" sample
 * in samples-data.ts, using the library's own renderer.
 *
 * The hero image has been regenerated by hand three times so far (see
 * `git log -- hero.png` / `hero.svg`), each time by manually screenshotting
 * the live demo. This script replaces that manual step so the README's
 * hero always matches whatever the "Hero" sample currently renders.
 *
 * Usage: tsx scripts/generate-hero.ts
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { samples } from '../samples-data.ts'
import { renderMermaidSVG } from '../src/index.ts'

const hero = samples.find((sample) => sample.category === 'Hero')
if (!hero) {
  throw new Error('No sample with category "Hero" found in samples-data.ts')
}

const svg = renderMermaidSVG(hero.source, hero.options)

const outPath = fileURLToPath(new URL('../hero.svg', import.meta.url))
writeFileSync(outPath, svg)

console.log(`Wrote ${outPath} (${svg.length.toLocaleString()} bytes)`)
