name: issue-bot

on:
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  issue-bot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: dfadler/issue-bot@0f14bb71f02ee14abf9f2f332bfe97d2ee11a272 # v1.2.0
