name: issue-bot

on:
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  issue-bot:
    permissions:
      issues: write
      pull-requests: write
    uses: dfadler/issue-bot/.github/workflows/reusable.yml@473c2eb4abbfb2be1980251f93ac6c9b2e3997c1 # v1.5.0
    with:
      ref: 473c2eb4abbfb2be1980251f93ac6c9b2e3997c1 # v1.5.0
